version: '3.8'

services:
  db:
    container_name: gateway_db
    image: postgres:latest
    environment:
      POSTGRES_DB: gateway_dev
      POSTGRES_PASSWORD: gateway_dev
      POSTGRES_USER: gateway_dev
    expose:
      - '5432'
    ports:
      - '5454:5432'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/

networks:
  default:
    name: gateway_net

volumes:
  postgres:
    driver: local
    name: gateway_db