Resources:
  # Target bucket for user uploads - scanned by ClamAV.
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: commons-gateway-${opt:stage}-upload
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ${file(./config/${param:deployment}.json):cors.headers}
            AllowedMethods:
              - PUT
            AllowedOrigins: ${file(./config/${param:deployment}.json):cors.origins}
            Id: commons-gateway-${opt:stage}-upload-cors
      Tags:
        - Key: application
          Value: gateway
        - Key: environment
          Value: ${opt:stage}

  # Bucket where successfully scanned files end up.
  CleanBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: commons-gateway-${opt:stage}-clean
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt SQSAprimoUpload.Arn
      Tags:
        - Key: application
          Value: gateway
        - Key: environment
          Value: ${opt:stage}

  # Bucket from which static site is served.
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: commons-gateway-${opt:stage}-site
      Tags:
        - Key: application
          Value: gateway
        - Key: environment
          Value: ${opt:stage}
