Resources:
  SecretJWT:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:custom.JWT_SECRET_NAME}
      Description: The secret used to sign JSON web tokens used a authorization grants.
      GenerateSecretString:
        PasswordLength: 40
        RequireEachIncludedType: true
      Tags:
        - Key: application
          Value: gateway
        - Key: environment
          Value: ${opt:stage}
